config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  delete "/" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  root to: 'orders#index', as: :list_orders
  post 'users/log_in' => 'users#log_in'
  resources :sessions
  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to: 'orders#search_by',
      as: :search_order_by,
      constraints: { field: /code|ext_code/ }

  resources :orders, only: [:show, :edit, :update, :index, :new, :create] do
    collection do
      get :process_cache
      get '/:type/:version/:value' => 'orders#change_cache_status', as: 'change_cache_status'
    end
  end
  post 'orders/:id' => 'orders#create'
  namespace :admin do
    post 'order_types/:order_type_id/update' => 'order_types#update', as: 'update_order_type'
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss,  on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
          constraints: ApiConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: { id: /.*/ }
      resources :orders, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/controllers/admin/order_types_controller.rb
class Admin::OrderTypesController < ApplicationController
  before_action :authenticate_user!
  self.hbw_available = true

  before_filter :require_order_type, only: [:show, :activate, :dismiss, :destroy]

  def index
    # @order_types = OrderType.active

    @order_types = []
    JSON.parse(RestClient.get(BACKEND_API_CONFIG['url'] + 'forms/types')).each_pair do |key, value|
      @order_types.push(name: value, code: key)
    end
    
    
  end

  def show
  end

  def update
    data = YAML::load(YAML::dump(params['order_type_form']['yaml']))    
    url = BACKEND_API_CONFIG['url'] + "forms/addOrderType" 
    begin
      @res = RestClient.post(url, data, 'Content-Type' => 'application/json')
    rescue => e
      @error = e.response.to_str
    end
    params[:id] = params[:order_type_id]

    respond_to do |format|
      format.html { redirect_to admin_order_type_path(params[:id]) }
      format.js do
        if !@res.nil? && @res.code == 200
          render json: 'Successfully updated!', status: 200
        else
          render json: @error.to_json, status: 402
        end
      end
    end
  end

  def create
    require 'yaml'
    file_content = params.require(:order_type).permit(:file)[:file].read
    @order_type = OrderType.new(file: file_content)
    @file = File.open(params[:order_type][:file].path())
      url = BACKEND_API_CONFIG['url'] + "forms/upload"
      request = RestClient::Request.new(
          :method => :post,
          :url => url,
          :enctype => "multipart/form-data",
          :payload => {
            :multipart => true,
            :file => @file
          })      

      begin
        # @res = RestClient.post(url, @file, 'Content-Type' => 'multipart/form-data', 'ENCTYPE' => "multipart/form-data", "Accept-Encoding" => "gzip, deflate")
        @res = request.execute
        @error = @res
      rescue => e
        @error = e.response.to_str
      end
      
      if !@res.nil? == 200 && @res.code
        render action: 'show'
      else
        @order_types = []
        render 'index'
        # redirect_to action: 'index' 
      end

    # if @order_type.valid?
    #   # 
            

    #   # @res = RestClient.post, file_content, :content_type => :json, :accept => :json
      
    #   # if @order_type.save_if_differs!
    #   #   flash[:success] = t('.uploaded')
    #   #   render action: 'show'
    #   # else
    #   #   flash[:error] = '%s: %s' % [t('.equal_exists'), @order_type.code]
    #   #   redirect_to action: 'index'
    #   # end
    # else
    #   flash[:error] = @order_type.errors.full_messages.join(', ')
    #   redirect_to action: 'index'
    # end
  end

  def destroy
    # @order_type.make_invisile
    @url = BACKEND_API_CONFIG['url'] + "forms/#{@order_type[:code]}"
    
    begin
      @res = RestClient.delete(@url)
      flash[:success] = t('.destroyed')
      redirect_to admin_order_types_path
    rescue => e
      @error = e.response.to_str + "<br>DETELE METHOD"
      @order_types = []
      render 'index'
    end
    
  end

  def activate
    @order_type.activate

    flash[:success] = t('.activated')
    redirect_to action: 'index'
  end

  def dismiss
    @order_type.destroy

    flash[:success] = t('.dismissed')
    redirect_to action: 'index'
  end

  def lookup
    render json: OrderType.lookup(params.require(:q)).to_json
  end

  private

  def require_order_type
    params[:id] = URI.decode(params.require(:id)).gsub('{dot}', '.')
    url = BACKEND_API_CONFIG['url'] + 'forms/json/' + params[:id]
    order_info = JSON.parse(RestClient.get(url))
    order_name = order_info['formName']
    order_code = order_info['code']
    url = BACKEND_API_CONFIG['url'] + 'forms/yaml/' + params[:id]
    yaml = RestClient.get(url)

    @order_type = {}
    @order_type[:name] = order_name
    @order_type[:code] = order_code
    @order_type[:active] = true
    @order_type[:yaml] = yaml
    @order_type[:html] = CodeRay.scan(yaml, :yml).div(
      tab_width: 0,
      css: :style,
      line_numbers: nil
    )

  end
end

app/views/admin/order_types/_activate_dismiss.html.haml
= link_to t('activate'), activate_admin_order_type_path(@order_type), method: :put, class: ' btn btn-danger'

= link_to t('dismiss'), dismiss_admin_order_type_path(@order_type), method: :delete, class: 'btn btn-primary'

app/views/admin/order_types/_upload.html.haml
= form_for :order_type do |f|
  = f.file_field :file, :type => 'file', 'data-show-preview'=> 'false', class: 'file'

app/views/admin/order_types/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')

.row
  .col-xs-12.col-sm-12.col-md-6.col-lg-6
    %table.table.table-hover.table-striped
      %thead
        %th= "Name" #OrderType.human_attribute_name(:name)
        %th(colspan="2")= t('activerecord.attributes.user.code')
      %tbody
        - @order_types.each do |order_type|
          %tr
            %td.order-name
              /order_type[:code].to_s.gsub(/\./,'{dot}')
              %a{ href: admin_order_type_path('car_init_1{dot}0') }= order_type[:name]
            %td= order_type[:code]
            %td
              = link_to(admin_order_type_path('car_init_1{dot}0'),
                        method: :delete,
                        class: 'text-danger',
                        data: { confirm: t('.confirmation', order_type: order_type[:name]), confirm_title: t('.order_type_removal'), confirm_proceed: t('.yes_remove') }) do
                %i.fa.fa-trash-o
  .col-xs-12.col-sm-12.col-md-6.col-lg-6
    %h5= t('.add')
    = render partial: 'upload'
%a.btn.btn-primary{ :href => BACKEND_API_CONFIG['url'] + "forms/download" }
  Download
/=debug(@error)
/debug(@url)
/debug(@file)

app/views/admin/order_types/show.html.haml
- content_for(:title, @order_type[:name])

%h2= @order_type[:name]
.row
  .col-xs-12.col-sm-12.col-md-8.col-lg-9
      
    .test-it-baby
      = simple_form_for('order_type_form',
                  remote: true,
                  url: admin_update_order_type_path(@order_type[:code].to_s.gsub(/\./,'{dot}')),
                  html: { role: 'form', id: 'new_order_form'}) do |f|
        %h3= t('Edit form definition')
        = f.input(:yaml, as: :text, input_html: {value: @order_type[:yaml], style: "height: 396px;"}, label: 'Json', required: false )
        = f.submit t('save'), class: 'btn btn-primary hbw-button pull-right'        

      / preserve(@order_type[:html].html_safe)
  .col-xs-12.col-sm-12.col-md-4.col-lg-3
    - if @order_type[:active]
      %div= t('.activated')
      = link_to admin_order_types_path do
        %i.fa.fa-long-arrow-left><
        = t('.back')
    - else
      %div= t('.activate_dismiss')
      = render partial: 'activate_dismiss'
/=debug(@error)
:coffee
$(document).ready ->
  
  a = 0
  $("#new_order_form").on("ajax:complete", (e, data, status, xhr) ->
    Application.messenger.show([["notice", data.responseText]])
    $('.hbw-button').attr('disabled',false)
  )
  $(document).bind("ajaxSend", () ->
     $('.hbw-button').attr('disabled', true)
     a++
     console.log('start' + a)
   ).bind("ajaxComplete", () ->
    $('.hbw-button').attr('disabled', false)
    console.log('finish')
   );