config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  delete "/" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  root to: 'orders#index', as: :list_orders
  post 'users/log_in' => 'users#log_in'
  resources :sessions
  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to: 'orders#search_by',
      as: :search_order_by,
      constraints: { field: /code|ext_code/ }

  resources :orders, only: [:show, :edit, :update, :index, :new, :create] do
    collection do
      get :process_cache
      get '/:type/:version/:value' => 'orders#change_cache_status', as: 'change_cache_status'
    end
  end
  post 'orders/:id' => 'orders#create'
  namespace :admin do
    post 'order_types/:order_type_id/update' => 'order_types#update', as: 'update_order_type'
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss,  on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
          constraints: ApiConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: { id: /.*/ }
      resources :orders, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/models/user.rb
class User #< ActiveRecord::Base
  class << self
    def id_from_email(email)
      select(:id).find_by(email: email).try(:id)
    end

    def lookup(q, limit = 10)
      s = q.mb_chars.downcase.to_s

      where(<<-SQL, *(["%#{s}%"] * 3))
        lower(name) like ?
          OR lower(last_name) like ?
          OR lower(middle_name) like ?
      SQL
        .select('id, name, middle_name, last_name')
        .order_by_name
        .limit(limit)
        .map { |u| { id: u.id, text: u.full_name } }
    end

    def order_by_name
      order(:name, :id)
    end

    def empty
      @empty ||= Empty.new
    end
  end

  include HasRole
  include HasApiToken

  default_scope { order(last_name: :asc, name: :asc, middle_name: :asc) }

  def full_name
    [name, last_name].join ' '
  end

  validates :name,        presence: true
  validates :last_name,   presence: true
  validates :company,     presence: true
  validates :department,  presence: true
end

app/controllers/api/v1/users_controller.rb
module API
  module V1
    class UsersController < API::BaseController
      include HttpBasicAuthentication

      PARAMS_ATTRIBUTES = [:name, :last_name, :middle_name, :company,
                           :department, :email, :role, :password]

      private

      def user_params
        params.require(:user).permit(*PARAMS_ATTRIBUTES).tap do |hash|
          hash[:password_confirmation] = hash[:password] if
            hash[:password]
        end
      end

      def resource_set(resource = nil)
        resource ||= resource_class.find_by_email!(params[:id])
        super resource
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  self.hbw_available = true

  PARAMS_ATTRIBUTES = [:name, :last_name, :middle_name, :company, :department,
                       :email, :role, :password, :password_confirmation]

  before_action :authenticate_user!
  #before_action :admin_only, except: [:show, :lookup]
  #before_action :find_user, except: [:new, :add, :index, :lookup]

  def index
    @users = getUserList
  end

  def show
    @user = JSON.parse(RestClient.get( BACKEND_API_CONFIG['url'] + "user/get/#{params[:id]}.com" ))
  end

  def update
    attributes = secure_params
    if attributes[:password].blank?
      attributes.delete(:password)
      attributes.delete(:password_confirmation)
    end
    if @user.update_attributes(attributes)
      redirect_to users_path, notice: t('user_updated')
    else
      render action: :edit
    end
  end

  def destroy
    user.destroy
    redirect_to users_path, notice: t('user_deleted')
  end

  def edit
  end
  def log_in
    redirect_to 'google.com'#controller: :orders,  action: :index
  end
  def new
    @user = User.new
  end

  def add
    post_params = {};
    if params['json_definition'].blank?
      temp = secure_params

      post_params['email'] = temp['email']
      post_params['pwd'] = temp['password']
      post_params['name'] = temp['name']
      post_params['last_name'] = temp['last_name']
      post_params['role'] = temp['role']
      post_params['company'] = temp['company']
      post_params['department'] = temp['department']
      post_params['status'] = 1
      @test = post_params
    else
      post_params = params['json_definition']
    end
    begin
      @res = RestClient.post BACKEND_API_CONFIG['url'] + "user/adduser", post_params.to_json, :content_type => :json, :accept => :json
      @req = @res.request
    rescue => e
      @error = e.response.to_str
    end
    if !@res.nil? && @res.code == 200
      flash = {success: 'Success!'}
    else
      flash = {error: @error + post_params.to_json}
    end
    redirect_to users_path, flash: flash
  end

  def generate_api_token
    @user.generate_api_token
    render action: 'show'
  end

  def clear_api_token
    @user.clear_api_token
    render action: 'show'
  end

  def lookup
    a = []
    users = []
    getUserList.each_with_index{|u, i|
      a.push ( {"id" => u['email'], "text" => u['email']} )
    }
    a.each do |u|
      users.push(u) if u['text'].include?(params[:q])
    end
    render json: users
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def admin_only
    redirect_to :back, alert: 'Access denied.' unless current_user.admin?
  end

  def secure_params
    params.require(:user).permit(*PARAMS_ATTRIBUTES)
  end
end

app/views/users/_form_fields.html.haml
= render partial: 'layouts/form_errors', locals: { record: @user }
/ = f.input :name, autofocus: true, required: false
/ = f.input :middle_name, required: false
/ = f.input :last_name, required: false
/ = f.input :email, required: false
/ - if @user == @current_user
/   = f.input :role do
/     %span.form-control
/       = roles_for_select.find { |(_, role)| role == @user.role }.first
/ - else
/   = f.input :role, as: :select, collection: roles_for_select
/ = f.input :company, required: false
/ = f.input :department, required: false
/ = f.input :password
/ = f.input :password_confirmation
= label_tag 'Json'
= text_area_tag :json_definition, 'enter json', html: {class: 'json_user-textarea'}

app/views/users/_user.html.haml
%tr
  %td
    %a{ href: user_path(user) }= user.full_name
  %td= user.email
  %td= t user.role_i18n_key
  %td= user.department
  %td= user.company
  %td= boolean_indicator(user.api_token?)

app/views/users/add.html.erb
<%=debug(@test)%>
<%=debug(@res.body)%>

app/views/users/edit.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
= simple_form_for(@user,
                  method: 'put',
                  wrapper: :horizontal_form,
                  html: { class: 'form-horizontal order-edit-form col-sm-6' }) do |f|
  = render partial: 'form_fields', locals: { f: f }
  = f.submit t('save'), class: 'btn btn-primary pull-right'

app/views/users/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= t('activerecord.attributes.user.full_name')
        %th= t('activerecord.attributes.user.email')
        %th= t('activerecord.attributes.user.role')
        %th= t('activerecord.attributes.user.department')
        %th= t('activerecord.attributes.user.company')
        %th= t('activerecord.attributes.user.api_token')
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user['name'].to_s + " " + user['last_name'].to_s, user_path(user['email'].to_s)
          %td= user['email']#.email
          %td= user['role']#t  .role_i18n_key
          %td= user['department']#.department
          %td= user['company']#.company
          %td= boolean_indicator(user['status'])#.api_token?)

= link_to t('new'), new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
- content_for(:title, t('.title'))
.authform
  = simple_form_for @user || :user, url: add_users_path, html: { role: 'form'} do |f|
    %h3= t('.title')
    = render partial: 'form_fields', locals: { f: f }
    = f.submit t('new'), class: 'btn btn-primary pull-right'

app/views/users/show.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    %p= "%s: %s"%[t('activerecord.attributes.user.full_name'), @user['name'] + " " + @user['last_name']]
    %p= "%s: %s"%[t('activerecord.attributes.user.email'), @user['email']]
    %p= "%s: %s"%[t('activerecord.attributes.user.role'), @user['role']]
    %p= "%s: %s"%[t('activerecord.attributes.user.company'), @user['company']]
    %p= "%s: %s"%[t('activerecord.attributes.user.department'), @user['department']]
    %p= "%s: %s"%[t('activerecord.attributes.user.api_token'), @user['api_token']]
    .row
      .col-xs-12
        = link_to t('edit'), edit_user_path, class: 'btn btn-primary'
        - if 1==1

          = link_to t('.renew_api_token'), "/", method: 'put', class: 'btn btn-danger', data: { confirm: 'Renew API Token', confirm_proceed: t('.yes_renew') }
          = link_to t('.clear_api_token'), "/",  method: 'delete', class: 'btn btn-danger', data: { confirm: t('.clear_api_token_warning'),  confirm_proceed: t('.yes_clear') }
        - else
          = link_to t('.generate_api_token'), "/", method: 'put', class: 'btn btn-primary'