config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  delete "/" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  root to: 'orders#index', as: :list_orders
  post 'users/log_in' => 'users#log_in'
  resources :sessions
  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to: 'orders#search_by',
      as: :search_order_by,
      constraints: { field: /code|ext_code/ }

  resources :orders, only: [:show, :edit, :update, :index, :new, :create] do
    collection do
      get :process_cache
      get '/:type/:version/:value' => 'orders#change_cache_status', as: 'change_cache_status'
    end
  end
  post 'orders/:id' => 'orders#create'
  namespace :admin do
    post 'order_types/:order_type_id/update' => 'order_types#update', as: 'update_order_type'
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss,  on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
          constraints: ApiConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: { id: /.*/ }
      resources :orders, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/models/order.rb
class Order # ActiveRecord::Base
  class << self
    def id_from_code(code)
      select(:id, :order_type_id).find_by(code: code).try(:id)
    end
  end

  include HasSequencedColumn
  has_sequenced_column :code

  belongs_to :order_type
  belongs_to :user

  validates :order_type, presence: true
  validates_with OrderDataValidator
  after_validation :coerce_values, if: -> rec { rec.errors.empty? }

  delegate :fields, :field_definition_set, to: :order_type
  delegate :name, :code, to: :order_type, prefix: true

  default_scope { includes(:order_type).order('created_at DESC') }

  enum state: %i(to_execute in_progress done)

  def user_full_name
    user ? user.full_name : ''
  end

  def self.state_i18n_key(state)
    "orders.states.#{state}"
  end

  def field_def_hash(name)
    order_type.fields[name.intern]
  end

  def order_type_id=(*)
    super.tap { initialize_fields }
  end

  def initialize_fields
    self[:data] = field_definition_set.nil_fields_values
  end

  def data=(hash)
    initialize_fields if data.nil?
    self[:data] = data.merge(hash)
  end

  private

  def coerce_values
    self[:data] = field_definition_set.coerce(data)
  end
end

app/models/order_type.rb
class OrderType #< ActiveRecord::Base
  class << self
    def lookup(q)
      s = q.mb_chars.downcase.to_s

      active.where('lower(name) like ?', "%#{s}%")
        .select('id, name')
        .order(name: :asc)
        .map { |e| { id: e.id, text: e.name } }
    end

    def id_from_code(code)
      active.select(:id).find_by(code: code).try(:id)
    end
  end

  include FileContainsYaml

  validates_with OrderTypeFileValidator

  has_many :orders
  before_destroy :check_for_orders

  serialize :fields
  # @order.data.each_pair
  scope :active, -> { where(active: true).order(name: :asc) }
  scope :code, ->(code) { where(active: true, code: code) }

  def initialize(*)
    super

    parse_file
  end

  def save_if_differs!
    last_one = self.class.code(code).last
    return false if self == last_one
    save!
  end

  def ==(other)
    other && other.code == code && other.fields == fields
  end

  def activate
    last_one = self.class.code(code).last
    transaction do
      last_one.update_column(:active, false) if last_one
      update_column(:active, true)
    end
  end

  def nil_fields_values
    field_definition_set.nil_fields_values
  end

  def field_definition_set
    CustomFields::FieldDefSet.new(fields)
  end

  def make_invisile
    update_attribute(:active, false)
  end

  private

  def parse_file
    OrderTypeFileValidator.new.validate self
    return unless errors.empty?

    self.fields = hash_from_file[:order_type][:fields]
    self.code   = hash_from_file[:order_type][:code]
    self.name   = hash_from_file[:order_type][:name]
  end

  def check_for_orders
    if orders.count > 0
      errors.add(:base, :cannot_delete_as_orders_exist)
      false
    else
      true
    end
  end
end

app/controllers/api/v1/orders_controller.rb
module API
  module V1
    class OrdersController < API::BaseController
      include HttpBasicAuthentication if !Rails.env.development? || ENV['HOMS_API_USE_AUTH']

      PARAMS_ATTRIBUTES = [:order_type_code, :user_email, :ext_code, :bp_id,
                           :bp_state, :state, :done_at, :archived]

      private

      def resource_set(resource = nil)
        resource ||= Order.find_by_code(params[:id])
        instance_variable_set("@#{resource_name}", resource)
      end

      def order_params
        p = params.require(:order).permit(*PARAMS_ATTRIBUTES).tap do |params|
          replace_user_email! params if params[:user_email]
          replace_order_type_code! params if params[:order_type_code]
        end

        params[:order][:data] ? p.merge(data: params[:order][:data]) : p
      end

      def replace_user_email!(params)
        user_id = User.id_from_email params[:user_email]
        replace!(params, :user_email, :user_id, user_id)
      end

      def replace_order_type_code!(params)
        order_type_id = OrderType.id_from_code params[:order_type_code]
        fail ActiveRecord::RecordNotFound unless order_type_id
        replace!(params, :order_type_code, :order_type_id, order_type_id)
      end

      def replace!(params, code_key, id_key, id_val)
        record_not_found unless id_val

        params.delete code_key
        params[id_key] = id_val
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < API::BaseController
  before_action :authenticate_user!
  self.hbw_available = true

  respond_to :html
  before_action :resource_set, only: [:create, :show, :new]

  def change_cache_status
    @url = BACKEND_API_CONFIG['url'] + 'user/cache/switch'
    data = {
      "userID" => current_user['email'],
      "type" => params[:type],
      "version" => params[:version],
      "value" => params[:value],
    }
    @user_caches = JSON.parse(RestClient.get("#{@url}?#{data.to_query}", :content_type => :json, :accept => :json))['userCache']
  end

  def process_cache
    @url = BACKEND_API_CONFIG['url'] + 'user/cache'
    data = {"userID" => current_user['email']}
    @user_caches = JSON.parse(RestClient.get("#{@url}?#{data.to_query}", :content_type => :json, :accept => :json))['userCache']
  end

  def show
    if params['unclaim']
      url = BACKEND_API_CONFIG['url'] +  "bpe/unclaimTask?userID=#{current_user['email']}&taskID=#{params[:id]}"
      begin
        @res = RestClient.get(url)
      rescue => e
        @error = e.response.to_str
      end

      if !@res.nil? && @res.code == 200
        flash = {success: 'Unclaimed!'}
      else
        flash = {error: @error}
      end
      redirect_to '/orders', flash: flash
    else
      url = BACKEND_API_CONFIG['url'] + 'bpe/claimTask/'
      url += '?userID=' + current_user['email']
      url += '&taskID=' + params[:id]
      begin
        @order[:raw] = JSON.parse(RestClient.get(url))
      rescue => e
        @error = e.response.to_str
        return redirect_to '/orders', :flash => { error: @error }
      end
      @order[:data] = prepared_order_fields(@order[:raw]['fields'])
      @order[:code] = params[:order_type_id]
    end
  end

  # GET /orders/search_by/{:code | :ext_code}/
  def search_by
    @criteria = "#{Order.human_attribute_name(params[:field])}: "\
                "'#{params[:value]}'"
    resource_set Order.find_by!(params[:field] => params[:value])
    render action: :show
  end

  def index
    #Main staff, fetch orders
    #@url = BACKEND_API_CONFIG['url'] + getQueryUrl
    #JSON.parse(RestClient.get(BACKEND_API_CONFIG['url'] + getQueryUrl))
    @orders = get_orders_from_api
    @orders = @orders#.paginate(:page => params[:page], :per_page => 10)
    #Filters staff
    @datetime_from = params[:created_at_from]
    @datetime_to = params[:created_at_to]

    @params_s = request.query_parameters
    if !params['user_id']&&!(@params_s[:filter]||@params_s[:commit])
      @users_for_pick = [current_user['email']]
    else
      @users_for_pick = [];
      @users_for_pick = params['user_id'] if(params['user_id'])
    end
  end

  def edit
  end

  def new
    if request.xml_http_request? #After order type chosen render fields else just render 'new'view
      url = BACKEND_API_CONFIG['url'] + 'forms/json/' +  params[:order_type_id]

      @order[:raw] = JSON.parse(RestClient.get(url))
      @order[:data] = prepared_order_fields(@order[:raw]['fields'])
      @order[:code] = params[:order_type_id]

      render partial: params[:partial_name]
    end
  end

  def create

    fields = {}
    #If create action performed after new action
    if params[:id].blank?
      url = BACKEND_API_CONFIG['url'] + 'forms/json/' +  params[:order_type_id]
    else # If action create being performed after show
      url = BACKEND_API_CONFIG['url'] + 'bpe/claimTask/'
      url += '?userID=' + current_user['email']
      url += '&taskID=' + params[:id]
    end
    @order[:raw] = JSON.parse(RestClient.get(url))
    raw = @order[:raw]

    raw['attribute'] = {
      'userId' => current_user['email'],
      'timestamp' => DateTime.now.to_time.to_i,
      "apiKey" => current_user['api_token']
    }

    unless raw['fields'].nil?
      raw['fields'].each do |field|
        if field['type'] == 'bool'
          val = params[:order_form][field['id']]
          params[:order_form][field['id']] = val == '0' ? false : true
        end
        field['value'] = params[:order_form][field['id']]
      end
    end
    begin
      @res = RestClient.post BACKEND_API_CONFIG['url'] + "bpe/do", raw.to_json, :content_type => :json, :accept => :json
    rescue => e
      @error = e.response.to_str
    end
    success = !@res.nil? && @res.code == 200

    respond_to do |format|
      format.html do
       if success
        flash = {success: 'Success!'}
       else
        flash = {error: 'Error!'}
       end
       redirect_to '/orders', flash: flash
      end
      format.js do
        if success
          render json: @res.body.to_json, status: 200
        else
          render json: @error.to_json, status: 402
        end
      end
    end
    # raw = []
    # raw_json_fields =  JSON.parse(@res.body)['fields']#.to_json
    # raw_json_fields.each do |order_type|

    # raw.push({
    #   :type => order_type['type'],
    #   :name => order_type['id'],
    #   :value => order_type['value'] || '',
    #   :label => order_type['label'],
    #   :can_edit => order_type['canEdit'],
    #   :order => order_type['order'],
    #   :value_set => order_type['valuesSet'] || ''
    #   })

    # end

    # raw.sort_by! {|order|
    #   order[:order]
    # }
    # @order = {}
    # @order[:data] = raw
    # @order[:code] = JSON.parse(@res.body)['code']
    # @order[:status] = @res.code.to_s + " " + @res.headers.to_s
  end
  def prepared_order_fields (raws)
    return if raws.nil?

    order_types = [];
    raws.each do |order_type|
      order_types.push({
        :type => order_type['visible'] ? order_type['type'] : 'hidden',
        :name => order_type['id'],
        :value => order_type['value'] || '',
        :label => order_type['label'],
        :can_edit => order_type['canEdit'],
        :order => order_type['order'],
        :value_set => order_type['valuesSet'] || ''
        })
    end
    order_types.sort_by! {|order|
      order[:order]
    }
    order_types
  end

  def get_orders_from_api

    @url = BACKEND_API_CONFIG['url'] + 'bpe/retrieveWorkListPage'
    data = {
        "userID" => current_user['email'],
        "offset" => (params[:page].to_i < 0 ? 0 : params[:page].to_i)*10,#per page
        "task" => (params[:state].present? ? params[:state] : ""),
        "process" => (params[:order_type_id].present? ? params[:order_type_id] : ""),
        "processNamesAsProzessname" => ""
    }

    JSON.parse(RestClient.get("#{@url}?#{data.to_query}", :content_type => :json, :accept => :json))#['items']
  end

  def getDateFromParams(key)
    date_raw = URI.unescape(params[key])[0...10]
    time_raw = URI.unescape(params[key])[11...19]

    date = Date.strptime(date_raw, "%m/%d/%Y")
    time = Time.strptime(time_raw, "%H:%M %p")
    return date.strftime("%Y-%m-%d") + "T" + time.strftime("%H:%M:%S") + ".434%2B0400"
  end

  def getParamsForApi
    parameters = {}
    params.each do |p|
      case p[0]
      when "order_type_id"
        parameters['orderType'] = params['order_type_id'] if params['order_type_id'] != ""
      when "state"
        parameters['orderStatus'] = params['state'] if params['state']  != ""
      when "archived"
        parameters['archived'] = params['archived'] if params['archived'] != ""
      when "user_id"
        next if params['user_id'] == ""
        str = ""
        params['user_id'].each_with_index do |u, index|
          str += "&userID=" if index != 0
          str += u
        end
        parameters['userID'] = str
      when "created_at_from"
        parameters['dateFrom'] = getDateFromParams('created_at_from') if params['created_at_from'] != ""
      when "created_at_to"
        parameters['dateTo'] = getDateFromParams('created_at_to') if params['created_at_to'] != ""
      when "value"
        parameters['code'] = params['value'] if params['value'] != ""
      when "code"
        parameters['businessID'] = params['code'] if params['code'] != ""
      else
      end
    end


    params_str = ""
    parameters.each { |p|
      params_str += p[0] + "=" + p[1] + "&"
    }
    params_str

  end

  def getQueryUrl

    params_str = getParamsForApi
    return "query?" + params_str unless params_str.empty?

    user = "&userID=#{current_user['email']}" if params['commit'] != "Search" && current_user
    user ||= ''

    "query?archived=0#{user}"
  end
  #**************USELESS SHIT*****************
  def update
    @order.data = params[:order]

    if @order.save
      redirect_to order_url(@order.code)
    else
      render 'edit'
    end
  end

  def set_order
    @order = Order.new
  end
  def get_field_def( name )

  end
  protected

  def resource_get
    instance_variable_get("@#{resource_name}")
  end

  helper_method \
  def list_filter
    @filter ||= ListOrdersFilter.new(current_user, filter_params)
  end

  def filter_params
    # user_ids = params[:filter] ? params[:user_id] : [current_user.id, 'empty']
    user_ids = {}
    params.permit(:state, :order_type_id, :archived,
                  :created_at_from, :created_at_to,
                  :filter, user_id: []).reverse_merge(user_id: user_ids,
                                                      archived: '0',
                                                      state: nil)
  end

  def record_not_found
  end

  def resource_set(resource = nil)
    @order = {}
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  EMPTY_VALUE = '—'.freeze

  def prettify_value(value, field = {})
    case field[:type]
      when 'datetime'
        prettify_date(value)
      when 'boolean'
        prettify_boolean(value)
      else value.to_s.presence || EMPTY_VALUE
    end
  end

  def prettify_date(value)
    if value.present?
      loc_datetime(value)
    else
      EMPTY_VALUE
    end
  end

  def prettify_boolean(value)
    if value
      '<i class="fa fa-check"></i>'.html_safe
    else
      ''
    end
  end

  def split_data(data, index = 10)
    data = (data.presence || {})
    visible, hidden = data.keys[0...index], data.keys[index..-1]
    [data.slice(*visible), data.slice(*hidden)]
  end
end

app/views/orders/_common.html.haml
.row
  .col-xs-6
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.ext_code')
        .value= prettify_value(@order.ext_code)
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.user')
        .value= prettify_value(@order.user_full_name)
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.state')
        .value= prettify_value(order_state_indicator(@order))
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.archived')
        .value= prettify_value(boolean_indicator(@order.archived))
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.created_at')
        .value= prettify_date(@order.created_at)
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.bp_state')
        .value= prettify_value(@order.bp_state)
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.bp_id')
        .value= prettify_value(@order.bp_id)
    .row.attribute-row
      .col-xs-12
        = succeed ':' do
          = t('activerecord.attributes.order.done_at')
        .value= prettify_date(@order.done_at)

app/views/orders/_data.html.haml
.row
  .col-xs-6
    - data.each_pair do |name, value|
      - field_def_hash = @order.field_def_hash(name)
      .row.attribute-row
        .col-xs-12{ title: field_def_hash.fetch(:description, '') }
          = succeed ':' do
            = field_def_hash.fetch(:label)
          .value
            = prettify_value(value, field_def_hash)

app/views/orders/_filter_by.html.haml
= form_tag(list_orders_path, method: :get, class: 'form-inline orders-filter') do
  %input(name="filter" value="true" type="hidden")
  .col-xs-12.col-sm-7.col-md-6.col-lg-7
    .row
      .col-xs-6.col-sm-6.col-md-6.col-lg-4
        %label(for="order_type_id")= t('helpers.enter_order_type')
        = order_type_picker(:order_type_id, value: list_filter.filter_values[:order_type_id])
      .col-xs-6.col-sm-6.col-md-6.col-lg-8
        %label(for="user_id")= t('helpers.enter_user')
        = user_picker(:user_id, value:  @users_for_pick)
    .row
      .col-xs-6.col-sm-6.col-md-6.col-lg-4
        %label(for="state")= t('helpers.enter_state')
        = order_state_picker(:state, value: list_filter.filter_values[:state])
    .row
      .col-xs-6.col-sm-6.col-md-6.col-lg-4
        %label(for="archived")= t('helpers.enter_archived')
        = order_archived_picker(:archived, value: list_filter.filter_values[:archived])
  .col-xs-12.col-sm-7.col-md-5.col-lg-4.padding-right-0px
    .row
      .col-xs-12.col-sm-12.col-md-12.col-lg-12.no-margin-bottom
        %label= t('helpers.creation_date')
      .col-xs-6.col-sm-12.col-md-12.col-lg-12
        .row
          .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
            %label(for="created_at_from")= t('helpers.from')
          .col-xs-10.col-sm-10.col-md-10.col-lg-10
            = datetime_picker(:created_at_from, value: @datetime_from)
      .col-xs-6.col-sm-12.col-md-12.col-lg-12
        .row
          .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
            %label(for="created_at_to")= t('helpers.to')
          .col-xs-10.col-sm-10.col-md-10.col-lg-10
            = datetime_picker(:created_at_to, value: @datetime_to)
  .col-xs-3.col-sm-2.col-md-1.col-lg-1.label-padding-top.label-padding-left-0px
    = submit_tag t('.search'), class: 'btn btn-primary'

app/views/orders/_form_field.html.haml
-disabled = field[:can_edit] ? '' : 'disabled'
- case field[:type]
  - when 'bool'
    = f.input(field[:name], as: :boolean, input_html: { checked: field[:value] == 'true', disabled + '' => ''  } , label: field[:label], required: false )
  - when 'datetime'
    = f.input :date_field, as: :date_picker, :label => 'Date field', input_html: {data: {date_options: {defaultDate: '2012/12/25'}}}
    / = f.input(field[:name], as: :datetime_picker, input_html: {value: field[:value], disabled + '' => ''}, label: field[:label], required: false )
  - when 'date'
    = f.input(field[:name], as: :datetime_picker, value: field[:value], input_html: {value: field[:value], disabled + '' => ''}, label: field[:label], required: false )
  - when 'string'
    = f.input(field[:name], as: :string, input_html: { value: field[:value] , disabled + '' => ''}, label: field[:label], required: false )
  - when 'float'
    = f.input(field[:name], as: :float, input_html: { value: field[:value] , disabled + '' => ''}, label: field[:label], required: false )
  - when 'int'
    = f.input(field[:name], as: :integer, input_html: { value: field[:value] , disabled + '' => ''}, label: field[:label], required: false )
  - when 'timedate'
    = f.input(field[:name], as: :datetime_picker, input_html: {value: field[:value], disabled + '' => ''}, label: field[:label], required: false )
  - when 'set'
    = f.label field[:label], field[:label]
    = dropdown_field_picker( 'order_form[' + field[:name] + ']', field[:value_set], input_html: {disabled:  disabled, selected: field[:value]})
  - when 'textarea'
    = f.input(field[:name], as: :text, input_html: {value: field[:value], disabled + '' => '', style: 'height: 115px;'}, label: field[:label], required: false )
  -when 'hidden'
    = f.input(field[:name],as: :hidden, input_html: {value: field[:value], disabled + '' => '', style: 'height: 115px;'}, label: field[:label], required: false )
  - else
    = t('error.types.undefined')

app/views/orders/_order.html.haml
%tr
  %td= link_to order['code'], order_path(order['code'])
  %td= order.order_type_name
  %td= order_state_indicator(order)
  %td= loc_datetime(order.created_at)
  %td= order.user_full_name
  %td= order.ext_code
  %td= boolean_indicator(order.archived)

app/views/orders/_search_by.html.haml
= form_tag(path, method: :get, class: 'form-inline') do
  .form-group
    = label_tag field, t('.search'), class: 'sr-only'
    = text_field_tag :value, field_value, placeholder: t(".#{field}"), class: 'form-control'
  = submit_tag t('.search'), class: 'btn btn-primary'

app/views/orders/_search_by_code.html.haml
= form_tag(path, method: :get, class: 'form-inline') do
  .form-group
    = label_tag field, t('.search'), class: 'sr-only'
    = text_field_tag :code, field_value, placeholder: t(".#{field}"), class: 'form-control'
  = submit_tag t('.search'), class: 'btn btn-primary'

app/views/orders/change_cache_status.js.haml
$(".loading").hide();
key = $('.user-cache-keys ').val()
$('.'+ key).removeClass('hide');
$(".user-cache-change-enable-status").html("#{ j render(:partial => 'orders/user_cache') }");

app/views/orders/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
= render partial: 'search_form'
.row
  .col-xs-12
    - if @orders.present?
      .table-responsive.orders-list
        %table.table.table-striped.table-hover
          %thead
            %tr
              %th= 'ID'#Order.human_attribute_name(:code)
              %th= 'Task Name' #Order.human_attribute_name(:order_type_code)
              %th= 'Process Name'#Order.human_attribute_name(:state)
              %th= 'Status'#Order.human_attribute_name(:created_at)
              %th= 'Created at'#Order.human_attribute_name(:user)
              %th= 'Business Key'#{title: Order.human_attribute_name(:ext_code)}= t('.ext_code')
              %th='Archived'#{title: Order.human_attribute_name(:archived)}= t('.archived')
          %tbody
            - @orders['items'].each do |order|
              %tr
                %td= link_to order['id'], order_path(order['id'])
                %td= order['taskName']#.order_type_name
                %td= order['processName']#_state_indicator(order)
                %td= order['status']
                //%td= boolean_indicator(!order['status'].blank?)
                %td= loc_datetime(order['taskCreationDate'])#order['user']#.user_full_name
                %td= order['businessKey']#.ext_code
                %td= boolean_indicator(!order['archived'].blank?)#.archived)

    - else
      %h4.empty-list= t('.no_orders_found')
  .pagination_2
    =link_to 'Prev', '/orders?page=' + prev_page_number(params['page']) + get_filter_params(params)
    =link_to 'Next', '/orders?page=' + next_page_number(params['page']) + get_filter_params(params)
= link_to t('add'), new_order_path, class: 'btn btn-primary'
/=debug(@url)
/=debug(@users_for_pick)

app/views/orders/new.html.haml
- content_for(:title, t('.title'))
.authform.new_order
  = render partial: 'new_form'

app/views/orders/process_cache.html.haml
.loading{style: "display:none"}
  %img{src: image_path("loading.gif")}

- content_for(:title, t('.cache-management'))
%h2= t('.cache-management')

- if @user_caches.present?
  .row
    .col-xs-6.col-sm-6.col-md-6.col-lg-4
      .margin-top-20
        %label= t('.process_type')
      .margin-top-10
      %select.form-control.order_type-picker.right-element.user-cache-keys
        = options_for_select(@user_caches.keys)

  .user-cache-change-enable-status
    = render partial: 'user_cache'

app/views/orders/show.html.haml
/  render partial: 'layouts/form_errors', locals: { record: @order }
- content_for(:title, @order[:raw]['formTitle'])
%div.content
 = simple_form_for('order_form',
                  url: "/orders/#{@order[:raw]['taskId']}",
                  html: { role: 'form', id: 'new_order_form'}, remote: true ) do |f|
  %h3= @order[:raw]['formTitle']
  -choose_decision_field = @order[:data].last
  -prevent_migration_field = @order[:data][@order[:data].length - 2]
  - @order[:data].each do |field|
   /Exit loop when done untill migration field
   - if field[:name] == '$preventMigration'
    -break
   = render partial: 'form_field', locals: { f: f, field: field}
  .submit-new-form-block.text-center

   = f.input(prevent_migration_field[:name], as: :boolean, input_html: { checked: prevent_migration_field[:value] == 'true'} , label: "Prevent Migration")
   %div
    = dropdown_field_picker( 'order_form[' + choose_decision_field[:name] + ']', choose_decision_field[:value_set])
   %div
    %div.btn.btn-warning.unclaim
     = link_to 'Unclaim', order_path(@order[:raw]['taskId'], { unclaim: true })

    = f.submit t(params['action'] == 'new' ? 'create' : 'start'), class: 'btn btn-primary hbw-button'

/$('.hbw-button').attr('disabled', false)
:coffee
$(document).ready ->
  $('.hbw-button').attr('disabled', true)
  $('.hbw-button').mousedown( () ->
     $('.hbw-button').attr('disabled',true)
     $('.unclaim').attr('disabled',true)

     $("#new_order_form").submit()
  )
  $(document).bind("ajaxSend", () ->
     $('.hbw-button').attr('disabled', true)
   ).bind("ajaxComplete", () ->
  );
  $("#new_order_form").on("ajax:complete", (e, data, status, xhr) ->
    responce = JSON.parse(JSON.parse(data.responseText));
    console.log(responce);
  )
  $('select[name="order_form[$userDecision]"]').change ->
    $('.hbw-button').attr('disabled', false)
    $('.hbw-button').val($(this).val())

  $('.order_type-picker.right-element').change ->
    $.ajax 'new',
      type: 'GET'
      dataType: 'html'
      data: {
        order_type_id: $('.order_type-picker.right-element').val()
        partial_name: "new_form"}
      success: (data, textStatus, jqXHR) ->
            $('.new_order').html(data)

  Application.enableDateTimePicker(true)
  Application.enableOrderTypePicker(true)

app/views/orders/test.html.erb
<%=debug(@orders)%>