config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  delete "/" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  root to: 'orders#index', as: :list_orders
  post 'users/log_in' => 'users#log_in'
  resources :sessions
  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to: 'orders#search_by',
      as: :search_order_by,
      constraints: { field: /code|ext_code/ }

  resources :orders, only: [:show, :edit, :update, :index, :new, :create] do
    collection do
      get :process_cache
      get '/:type/:version/:value' => 'orders#change_cache_status', as: 'change_cache_status'
    end
  end
  post 'orders/:id' => 'orders#create'
  namespace :admin do
    post 'order_types/:order_type_id/update' => 'order_types#update', as: 'update_order_type'
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss,  on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1,
          constraints: ApiConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: { id: /.*/ }
      resources :orders, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/views/layouts/_form_errors.html.haml
- if record.errors.any?
  #error_explanation.alert.alert-danger
    .alert.alert-danger
      = t('.errors', count: record.errors.count)
    %ul
      - record.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle(data-target=".navbar-collapse" data-toggle="collapse" type="button")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse
      %ul.nav.navbar-nav
        %li.logo
          = link_to list_orders_url  do
            = 'PCS'
            %img{src: image_path("logo.jpg")}
        - if current_user
          %li
            = link_to orders_path do
              %span.glyphicon.glyphicon-list
              = t('.orders')
          - if admin?(current_user)
            %li
              = link_to admin_order_types_path do
                %span.glyphicon.glyphicon-cog
                = t('.setup_order_types')
            %li
              = link_to users_path do
                %span.fa.fa-users
                = t('.users')
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            = link_to('#', class: 'dropdown-toggle', role: :button, 'data-toggle' => 'dropdown') do
              %span.fa.fa-user
              = current_user['name']
              %span.caret
            %ul.dropdown-menu{role: :menu}
              %li
                = link_to "Process Cache", process_cache_orders_path

              - link_to_manual = Rails.application.config.app.fetch(:link_to_manual, '')
              - if link_to_manual.present?
                %li
                  %a(href="#{link_to_manual}")
                    %span.glyphicon.glyphicon-question-sign
                    = t('.help')
              %li
                = link_to :log_out, :method=>'delete' do
                  %span.glyphicon.glyphicon-log-out
                  = t('.sign_out')

          %li#hbw-tasks-list-button.hbw-styles
            %a.hbw-menu-button.my-items.fa.fa-reorder{:href => "javascript:;"}
              - my_item_list = my_items
              %span.counter= my_item_list.count


- if current_user
  #hbw-tasks
    %div
      .hbw-sheet.hbw-enabled.col-xs-12.col-sm-4.col-md-3.col-lg-2
        .hbw-sheet-header
          .hbw-sheet-header-container
            .hbw-sheet-header-title-container
              %em.hbw-sheet-header-title.my-task-title
                %b My Tasks
            %a.hbw-sheet-header-button.hbw-sheet-header-close-button
              .hbw-sheet-header-button-icon.hbw-sheet-header-close-button-icon
        .hbw-sheet-body
          %div
            %ul.hbw-task-item
            - my_item_list.each do |myitem|
              %li.hbw-inactive-task
                %span
                  = link_to myitem['id'], order_path(myitem['id'])
                  \ - #{myitem['taskName']} [#{myitem['processName']}]

app/views/layouts/application.html.haml
!!!
%html.hbw-styles
  %head
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Homs'
    %meta{ name: 'description', content: "#{content_for?(:description) ? yield(:description) : 'Homs'}"}
    = stylesheet_link_tag 'hbw', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'hbw'
    = javascript_include_tag "application", params[:controller]
    = csrf_meta_tags
  %body.hbw-select2
    :javascript
      I18n.locale = '#{I18n.locale}'
    %header
      = render 'layouts/navigation'
      = Rails.application.config.app.fetch(:announcement, '').to_s.html_safe

    %main.container(role="main")
      .container= yield

    - if flash_messages.any?
      :javascript
        console.log(#{flash_messages.to_json});
        Application.messenger.show(#{flash_messages.to_json});
    / - if hbw_available?
    /   #hbw-tasks
    /   :coffee
    /     window.HBWidget = new (modulejs.require('HBW'))(#{hbw_options.to_json})